[package]
name = "repro"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
futures = "0.3.10"
observability = "0.1"
tokio = { version = "1", features = [ "full" ] }
tracing = "0.1"

[workspace]
