name: CI

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable, 1.45.0, 1.42.0, 1.31.0]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - if: matrix.rust == '1.31.0'
        run: echo 'extern crate proc_macro;' >> demo-hack-impl/src/lib.rs
      - run: cargo run --manifest-path example/Cargo.toml
      - run: cargo test --all
