name: WINREPRO

on:
  push:
  pull_request:

jobs:
  repro:
    name: Repro
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --all-features --manifest-path repro/Cargo.toml
